# Flux analysis

## 1. Install requirements

In [1]:
!pip install -r requirements.txt

Requirement already satisfied: numpy in /home/juanessao2000/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: photutils in /home/juanessao2000/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied: astropy in /home/juanessao2000/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (5.3.4)
Requirement already satisfied: pyerfa>=2.0 in /home/juanessao2000/anaconda3/lib/python3.11/site-packages (from astropy->-r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: PyYAML>=3.13 in /home/juanessao2000/anaconda3/lib/python3.11/site-packages (from astropy->-r requirements.txt (line 3)) (6.0.1)
Requirement already satisfied: packaging>=19.0 in /home/juanessao2000/anaconda3/lib/python3.11/site-packages (from astropy->-r requirements.txt (line 3)) (23.2)

## 2. Import libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## 3. Data Analysis

### 3.1 IRAC

Charge the data resulting from the code run in the [IRAC notebook](./IRAC_notebook.ipynb)

In [7]:
irac_df = pd.read_csv("Data/IRAC_outputs/Table_IC348.csv")
irac_df

,Unnamed: 0,OBJECT_ID,RA,DEC,1_mag_0,1_mag_err_0,DATE-OBS_1_mag_0,4_mag_0,4_mag_err_0,DATE-OBS_4_mag_0,3_mag_0,3_mag_err_0,DATE-OBS_3_mag_0,2_mag_1,2_mag_err_1,DATE-OBS_2_mag_1
0,0,2.1662781242585843e+,56.140769,31.975080,13.551206,0.016778,2004-02-11T00:28:54.703,12.553866,0.087101,2004-02-11T00:28:54.703,13.057037,0.033857,2004-02-11T00:28:54.703,13.282787,0.017354,2004-02-11T00:28:54.703
1,1,2.1662911380012454e+,56.213663,31.986909,17.590223,0.163271,2004-02-11T00:28:54.703,17.488334,7.978432,2004-02-11T00:28:54.703,17.746114,2.103566,2004-02-11T00:28:54.703,17.631748,0.179780,2004-02-11T00:28:54.703
2,2,2.16629530412699e+17,56.219711,32.015701,13.797731,0.018872,2004-02-11T00:28:54.703,13.633916,0.231496,2004-02-11T00:28:54.703,13.653674,0.054546,2004-02-11T00:28:54.703,13.718890,0.021307,2004-02-11T00:28:54.703
3,3,2.1662973227464986e+,56.254507,32.040566,15.496543,0.044277,2004-02-11T00:28:54.703,15.296061,1.061363,2004-02-11T00:28:54.703,15.418542,0.252273,2004-02-11T00:28:54.703,15.365313,0.047552,2004-02-11T00:28:54.703
4,4,2.1662987401007654e+,56.267739,32.051545,15.171091,0.037285,2004-02-11T00:28:54.703,14.987270,0.799229,2004-02-11T00:28:54.703,14.859006,0.153234,2004-02-11T00:28:54.703,15.061621,0.040791,2004-02-11T00:28:54.703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,564,2.1671903753111283e+,56.086957,32.345535,13.860935,0.019452,2004-02-11T00:28:54.703,13.953402,0.309880,2004-02-11T00:28:54.703,13.893898,0.066597,2004-02-11T00:28:54.703,13.872160,0.022910,2004-02-11T00:28:54.703
565,565,2.1671931240902336e+,56.022659,32.331783,16.714138,0.089925,2004-02-11T00:28:54.703,16.511700,3.246798,2004-02-11T00:28:54.703,17.091543,1.154097,2004-02-11T00:28:54.703,16.693045,0.098460,2004-02-11T00:28:54.703
566,566,2.1671927375378483e+,56.046041,32.328156,14.152369,0.022391,2004-02-11T00:28:54.703,14.277243,0.416738,2004-02-11T00:28:54.703,14.222342,0.087995,2004-02-11T00:28:54.703,14.050628,0.024940,2004-02-11T00:28:54.703
567,567,2.167193081128224e+1,56.020875,32.334301,20.270370,1.510223,2004-02-11T00:28:54.703,17.917746,11.847848,2004-02-11T00:28:54.703,17.996130,2.646576,2004-02-11T00:28:54.703,19.934312,1.119407,2004-02-11T00:28:54.703
568,568,2.1671924368954765e+,56.023281,32.325271,15.293922,0.039757,2004-02-11T00:28:54.703,15.271747,1.037912,2004-02-11T00:28:54.703,14.169737,0.084121,2004-02-11T00:28:54.703,15.181055,0.043309,2004-02-11T00:28:54.703

The only meaningful data is the one that has possitive uncertainty value. Let's filter it.

In [9]:
N_irac_channels = 4
for ch in range(N_irac_channels):
    irac_df = irac_df[irac_df[f"{ch+1}_mag_err_0"] > 0]

KeyError: '2_mag_err_0'